# Generated by Django 5.2.4 on 2025-07-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tarea",
            new_name="ToDo",
        ),
    ]
