# Generated by Django 5.2.4 on 2025-07-22 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_tarea_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameOfLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "incertidumbre",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "segundos_por_tick",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.001)]
                    ),
                ),
                ("dimension", models.JSONField()),
                ("matriz", models.JSONField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
